language: node_js
node_js:
 - "node"
services:
 - postgresql
before_script:
 - psql -c 'CREATE DATABASE palettes_test;' -U postgres
 - npm run migrate-test
 - npm run seed-test
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: rT39Dq0l6bSQbzokLZc6HMasjZY5YMRvlSzwN5mGcK3HrELfAa9+dZs8tkcI3F+UMOf7xSdjJQEIMcoAKNtRd4kL099/TgVovPFJPN7hQbE4MxKExxZb6fXo1hn8Ar+wVgbPGxziPfvzXIEOvHGRWlJEPwR/FE7GvtMu1jRjGkgs2OfnVVGp9PiZfqjIWMrzHuS36pSkIB4UHilhDIAsyuDbtlJJ1/ZctchI/3ave+DH2M2NBUMD21o4g0ok0KE93dgxr9iPxnxI0uUdCQAsS4mzWknMZtlvFEuLuJSFl8QbYjjngdWQNxLNxiFg80KGsPM/o8jXMpxRBsZXFpKDfIFT3P4qMZdOkRCzQKF5KjntKcib5gMOu3d6vhCnk+IQLp5nczviytUjFno121KFCU4k03uUOmEy1hB0il9izz/eHgLO3tCuDUxBgVLhJaU3a9JNHYPjzJof1AlKb0t5hkIuDZGSL0O0QuD5nng0vOGi2CCZRfoGYwhFdLGbeyxSiTgLH7ZDeMszH3tv/b5y0YNrhu2QMHSHm2XUPiSxMlY3hMG7Lx+QeZSEydg/Mnqr8EJexgh5bfQKL8aFWPgX3gEDIlfb4zC/8osBXi0tqLIqeFxEC3/CsGg9CHFPdNsWpqHlsgQGR/9PBik9CqKnt17bOS/fk/Nn7u8Kp9rB/6c=
  app: palette-pal-be
  skip_cleanup: true