language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE palettes_auth_test;' -U postgres
- npm run migrate-test
- npm run seed-test
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: myzC+yteKhhsuVtvwS9k2tNh5bjZRjuPlDLwSKZnWZshIuGnvS7YBnHUkXptLX+Xnc09VGSdNRqiN6poWL9oVi/ePNPIUWfnBSVfcTcPzpkHj9ZFE5GOaoWBauV/Ac8K0H6ur9SNGopNOMSaheosql4aCUhzTsujdOJCCIdauOkElnJEEZI4aJ6C87wtQQlyzOiRZFzNrducvMq6SmkPr6qPWVdfSd5vIZbjVwh0VE4qvkSi27+KZ/+bD6NFVmo6kcgH2PD5GaOci0LGDDEydQVUnRlfB9VWgn28Iyp3dJr6d/Lo4HzcqdNpRfiJcwuVcspv8W9CdspkV9LRmSm6ubEbRSz9MZIYB0DNDLSzG6V5W/6+49UGQIkT8J4gWUqA0bbk9B/QpPADzoiKbQ3NxP3cTjp7WjmQR+8PNy3oMYhDQ2yVTiN3Bhgmtzp8Pc13VvMdqyfwRg3X6au24fvdH6Gycvd0r5p8GyzOgOB72hPg+B3pSC9j2kXyiX+OPdVY4gtz4PHV3fmS+g1c7UVXDn7CiCGZfqzxGgsKsiEw6ioBChus1wuW+2JNj2sR+/i/S1+xThrkESmGEET9KKLeau00JMaOP0jCYvOAYRS2tPfHwgzbKuTmA2B4LEzm8TmpP0u5Scv7bDdQ/684hEbnjvfBCLM0I7/AwWt/lIdpj4E=
  app: palette-pal-be
  skip_cleanup: true
