language: node_js
node_js:
- node
services:
- postgresql
before_script:
- npm install dotenv
- psql -c 'CREATE DATABASE palettes_auth_test;' -U postgres
- npm run migrate-test
- npm run seed-test
script:
- npm run test
- npm run test-auth
- npm run test-middleware
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: VoLEafn7yw0w+yOo/dSKUGw2ZgduslLOyczTUKtb3v+MxN6KhD8+Nf7/scappB12w8M/m1YingpR8OsHOsF5uDBlmknuoMk9kPsPYIFvqJlUhKJOnb+P0XZqih6LePHqXaRe/W7W/blnNwQtqq+TI72cJ2gYijQZlPaE3ccCSUIZvStWlyuulx0uBTL5JxS1gTsu9x1cxjqZFWA8RmdT5NzMqX77KMUG84SWKK5X54BqDsuyswnEVZqZg49zonRDuHI4P6VzodJNZ3tDuZ1LuWlOaQWWH1ZaInkVDGsIz9eu8Ptkvo9GOWh28UMdZPiuIffcthdZTueCsG6hzfLn4FL6btYeAPaDihp3/ovUUfmk7s3DJ/9GI5bBs6V1PZBxQ09rkU+d6SqK0aX/5pFn3fiV+H62LHQQt3HgsN4WHlm4rJH+wocgkh/+hfbkcUf0hBHdTqoOmOxhqK1pM55Dr1aFvf2f3vLWHLh322JMaKX7W+VuxsUo2+TJbUl/TLklEtGAyezh59OI9rEl6WYe8FtfWZHoSr5JDinftJKHGu4GaWX396CuMu71cKRBR5z/YvvuhiQwGJcuPGJkHULf+s4VvHTgDEjiQhMHbtoeH4mfR2vPjgTVu/49TEUXEYuaovEBXhSOCQtelGiv+tG/coxLy5BccsUSEzwubskrMhE=
  app: palette-pal-be
  skip_cleanup: true
